namespace Itmo.ObjectOrientedProgramming.Lab4.Presentation.ArgumentParser.Arguments.ConcreteArguments.ShowCommandModeArgumentFactories;

public interface IShowCommandModeArgumentFactoryLink : IShowCommandModeArgumentFactory
{
    IShowCommandModeArgumentFactoryLink AddNext(IShowCommandModeArgumentFactoryLink link);
}