namespace Itmo.ObjectOrientedProgramming.Lab4.Presentation.ArgumentParser.Arguments.ConcreteArguments.ConnectCommandModeArgumentFactories.ConnectCommandModeArgumentFactoryFactories;

public interface IConnectCommandModeArgumentFactoryFactory
{
    IConnectCommandModeArgumentFactory Create();
}